//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BankingPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class login_table
    {
        public int login_id { get; set; }
        public string username { get; set; }
        public string passwords { get; set; }
        public string roleofuser { get; set; }
        public string token { get; set; }
    }
}
