//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BankingPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class customers_table
    {
        public int cusid { get; set; }
        public string cusname { get; set; }
        public string cusaddress { get; set; }
        public string cusstatus { get; set; }
    }
}
