//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestaurantSite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class customerdetail
    {
        public int booking_id { get; set; }
        public Nullable<int> table_number { get; set; }
        public string customer_name { get; set; }
        public Nullable<long> mobile_no { get; set; }
        public Nullable<bool> checkedout { get; set; }
    
        public virtual tabledetail tabledetail { get; set; }
    }
}
