//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestaurantSite.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class masterEntities : DbContext
    {
        public masterEntities()
            : base("name=masterEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<customerdetail> customerdetails { get; set; }
        public virtual DbSet<tabledetail> tabledetails { get; set; }
    
        public virtual int sp_updateoccupancystatus(Nullable<int> tableno)
        {
            var tablenoParameter = tableno.HasValue ?
                new ObjectParameter("tableno", tableno) :
                new ObjectParameter("tableno", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_updateoccupancystatus", tablenoParameter);
        }
    }
}
