//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestaurantSite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tabledetail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tabledetail()
        {
            this.customerdetails = new HashSet<customerdetail>();
        }
    
        public int table_number { get; set; }
        public int capaciyoftable { get; set; }
        public bool istableoccupies { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<customerdetail> customerdetails { get; set; }
    }
}
